import type { Item } from "@/lib/types";

export const items: Item[] = [
  {
    id: "urea-001",
    name: "Premium Urea Fertilizer",
    description:
      "Pure nitrogen compound for broad-spectrum crop enhancement in rice and corn.",
    price: 1240.5,
    unit: "per 50kg bag",
    image: "/items/fertilizer.svg",
    category: "Fertilizer",
    location: "Nueva Ecija",
    seller: "Luzon Agro Supplies",
    rating: 4.8,
    quantity: 24,
    status: "available",
  },
  {
    id: "seed-014",
    name: "Hybrid Rice Seeds",
    description:
      "High-yield hybrid variety bred for wet-season planting with good lodging resistance.",
    price: 680,
    unit: "per 5kg pack",
    image: "/items/seeds.svg",
    category: "Seeds",
    location: "Isabela",
    seller: "Maya Seed Farm",
    rating: 4.7,
    quantity: 8,
    status: "low-stock",
  },
  {
    id: "soil-007",
    name: "Organic Vermicast",
    description:
      "Nutrient-rich worm castings for soil conditioning and slow-release feeding.",
    price: 320.75,
    unit: "per 20kg bag",
    image: "/items/soil.svg",
    category: "Soil Amendment",
    location: "Laguna",
    seller: "GreenLoop Farms",
    rating: 4.9,
    quantity: 0,
    status: "out-of-stock",
  },
  {
    id: "corn-031",
    name: "Yellow Corn Seeds",
    description:
      "Drought-tolerant hybrid corn variety suited to dry-season cultivation.",
    price: 540,
    unit: "per 4kg pack",
    image: "/items/corn.svg",
    category: "Seeds",
    location: "Pampanga",
    seller: "AgriCentro Pampanga",
    rating: 4.5,
    quantity: 15,
    status: "available",
  },
  {
    id: "fert-092",
    name: "Liquid Foliar Fertilizer",
    description:
      "Fast-absorbing foliar formula that boosts flowering and fruit setting.",
    price: 899,
    unit: "per 1L bottle",
    image: "/items/fertilizer.svg",
    category: "Fertilizer",
    location: "Davao City",
    seller: "Davao Agrochem",
    rating: 4.6,
    quantity: 30,
    status: "available",
  },
  {
    id: "seed-056",
    name: "Vegetable Seeds Bundle",
    description:
      "Curated bundle of pechay, tomato, and eggplant seeds for backyard gardens.",
    price: 250,
    unit: "per box",
    image: "/items/vegetables.svg",
    category: "Seeds",
    location: "Bukidnon",
    seller: "Highland Harvest",
    rating: 4.4,
    quantity: 6,
    status: "low-stock",
  },
  {
    id: "feed-021",
    name: "Hog Feed Starter",
    description:
      "Balanced starter ration for piglets with essential vitamins and minerals.",
    price: 1050,
    unit: "per 25kg sack",
    image: "/items/feed.svg",
    category: "Animal Feed",
    location: "Batangas",
    seller: "Batangas Feed Mill",
    rating: 4.3,
    quantity: 18,
    status: "available",
  },
  {
    id: "tool-018",
    name: "Hand Shovel Set",
    description:
      "Durable pair of stainless hand shovels for transplanting and soil work.",
    price: 185,
    unit: "per set of 2",
    image: "/items/tools.svg",
    category: "Farm Tools",
    location: "Bulacan",
    seller: "Kabo Tools",
    rating: 4.2,
    quantity: 40,
    status: "available",
  },
  {
    id: "pest-033",
    name: "Insecticide Spray",
    description:
      "Broad-spectrum insecticide protecting rice and vegetable crops from pests.",
    price: 425,
    unit: "per 500mL bottle",
    image: "/items/pesticide.svg",
    category: "Pesticide",
    location: "Quezon",
    seller: "Sierra Crop Care",
    rating: 4.5,
    quantity: 5,
    status: "low-stock",
  },
];

export const categories = [
  "All",
  ...Array.from(new Set(items.map((item) => item.category).filter(Boolean))),
] as string[];
